name: PRLifeMobile
options:
  bundleIdPrefix: com.pramitranjan.prlife
  deploymentTarget:
    iOS: "17.0"
packages:
  PRLifeKit:
    path: .
targets:
  PRLifeMobile:
    type: application
    platform: iOS
    sources:
      - App
    dependencies:
      - package: PRLifeKit
      - target: PRLifeWidgets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pramitranjan.prlife
        INFOPLIST_FILE: App/Resources/Info.plist
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: App/PRLifeMobile.entitlements
  PRLifeWidgets:
    type: app-extension
    platform: iOS
    sources:
      - Widgets
      - path: App/Activity/RecordingAttributes.swift
    dependencies:
      - package: PRLifeKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pramitranjan.prlife.widgets
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Widgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: Widgets/PRLifeWidgets.entitlements
schemes:
  PRLifeMobile:
    build:
      targets:
        PRLifeMobile: all
    run:
      config: Debug
    test:
      config: Debug
